# tool-tool configuration file - cf. https://gitlab.com/manuelwoelker/tool-tool/-/blob/master/README.md
tools:
  - name: lsd
    version: 0.17.0
    download:
      linux: https://github.com/Peltoche/lsd/releases/download/${version}/lsd-${version}-x86_64-unknown-linux-gnu.tar.gz
      windows: https://github.com/Peltoche/lsd/releases/download/${version}/lsd-${version}-x86_64-pc-windows-msvc.zip

  - name: Node.js
    version: 12.18.2
    download:
      linux: https://nodejs.org/dist/v${version}/node-v${version}-linux-x64.tar.gz
      windows: https://nodejs.org/dist/v${version}/node-v${version}-win-x64.zip
    commands:
      node: ${linux:bin/node}${windows:node}
      npm: ${linux:bin/npm}${windows:npm}
      npx: ${linux:bin/npx}${windows:npx}

  - name: Yarn
    version: 1.22.4
    download:
      default: https://github.com/yarnpkg/yarn/releases/download/v${version}/yarn-v${version}.tar.gz
    commands:
      yarn: ${cmd:node} ${dir}/bin/yarn.js
      tool-tool-shim: ${cmd:node} ${dir}/bin/yarn.js